/* keyboard uid */
#define VIAL_KEYBOARD_UID {0xDC, 0x6D, 0x9C, 0x42, 0x53, 0x42, 0x75, 0x0F}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 4 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 5 }

#define COMBO_ONLY_FROM_LAYER 0

/* default layer count */
#define DYNAMIC_KEYMAP_LAYER_COUNT 10

#define BILATERAL_COMBINATIONS
#define BILATERAL_COMBINATIONS_TYPING_STREAK_TIMEOUT 280 // Default 175
#define BILATERAL_COMBINATIONS_ALLOW_SAMESIDED_AFTER 500
#define BILATERAL_COMBINATIONS_ALLOW_CROSSOVER_AFTER 130 // Default 75
